### PR TITLE
Solved Bug: UD-594

### PR DESCRIPTION
**Pull request by GAOChengzhan**
1. Created a map which maps **_the Type of Visual Property_** to _**the Type of Attribute**_

| Type of Visual Property |  Type of Attribute |
| ------------- | ------------- |
| color  | string |
| opacity | CX_NUMBER_DATATYPES |
| nodeShape  | string |
| number  | CX_NUMBER_DATATYPES |
| fontFamily  | string |
| string  | string |
| labelPosition  | string |
| visibility  | boolean |
| edgeBend  | string |
| line  | string |
| arrow  | string |

2. Created a Validation Function, `mappingFunctionValidator`, for the `styleMapping` function, and ensured it is invoked prior to calling `styleMapping`  function
3. Added a unit test for the newly created Validation Function in the test file.

### CODE REVIEW

**Review by jingjingbic — CHANGES_REQUESTED** [review]
A couple of things:

1. in the mapping table opacity should be a number (integer or float). and visibility should be boolean
2. mapping on string type should always be treated as valid. for example on opacity or number.

Could you make these changes?

**Comment by GAOChengzhan** [comment]
> A couple of things:
> 
> 1. in the mapping table opacity should be a number (integer or float). and visibility should be boolean
> 2. mapping on string type should always be treated as valid. for example on opacity or number.
> 
> Could you make these changes?

Okay, done.

-  I changed the mapping table accordingly. In the code the visibility was actually mapped to boolean but I mistakenly typed string in the above github comment.
- I also added an `if `statement to see whether the type in the definition is string or not. If yes, return true directly.

**Comment by GAOChengzhan** [comment]
### A new BUG was caught
If the `visualProperty` passed to the `mappingFunctionValidator` function is NOT included in the `visualPropertyMap`, an error would come up since the `visualPropertyMap` seems to not cover all the existing visual properties.
 ### Solution
Only check the validation of the mapping function when the `visualProperty` does exist in the `visualProperty`.
#### PS:
For now, it is also assumed that all the `definition` passed to the `mappingFunctionValidator` is validated and legal.

**Comment by GAOChengzhan** [comment]
Solved the two versions' conflicts (kept the version from `develop` branch for conflict files).

**Review by jingjingbic — APPROVED** [review]

**Pull request merged**
